INSERT INTO studio (name, found_date, country, studio_logo) values
('Konami', '1969-03-21', 'Japan', 'images/Konami.png'),
('Capcom', '1979-05-30', 'Japan', 'images/Capcom.png'),
('Sony Interactive Entertainment', '1993-11-16', 'Japan', 'images/SIE.png'),
('Namco', '1955-06-01', 'Japan', 'images/Namco.png'),
('Electronic Arts', '1982-05-27', 'USA', 'images/EA.png'),
('Polyphony Digital', '1994-12-16', 'Japan', 'image/Polyphony.png'),
('Nintendo', '1889-08-23', 'Japan', 'image/Nintendo.png'),
('Sega', '1960-06-03', 'Japan', 'image/Sega.png'),
('Game Freak', '1989-04-26', 'Japan', 'images/GameFreak.png'),
('Treasure', '1992-06-19', 'Japan', 'images/Treasure.png'),
('Core Design', '1988-05-13', 'England', 'images/CoreDesign.png'),
('Activision', '1979-10-01', 'USA', 'images/Activision.png');

INSERT INTO platform (name, cpu_name, cpu_clock_speed, memory, internal_storage, platform_logo) values
('Playstation', 'R3000', 33.8688, 3, 0, 'console_logo/playstation.img'),
('Atari Jaguar', 'Motorola 68000', 13.295, 2, 6, 'console_logo/atari_jaguar.img'),
('Sega Saturn', 'Hitachi SH-2 (x2)', 28.6, 4, 0, 'console_logo/sega_saturn.img'),
('Virtual Boy', 'NEC V810', 20, 0, 0, 'console_logo/virtual_boy.img'),
('Nintendo 64', '64-bit NEC VR4300', 93.75, 8, 64, 'console_logo/nintendo_64.img');

INSERT INTO game (title, released_date, genre, game_logo, rating, description, studio_id) values
('Castlevania', '1997-03-20', 'RPG', 'images/Castlevania.png', '9.0',
 'Castlevania: Symphony of the Night is a platform-adventure action role-playing game developed and published by Konami in 1997 for the PlayStation.',
    (SELECT id from studio where name = 'Konami')),
('Crash Bandicoot', '1996-08-09', 'TPP', 'images/CrashBandicoot.png', '8.5',
 'Crash Bandicoot is a 1996 platform video game developed by Naughty Dog and published by Sony Computer Entertainment for the PlayStation.',
 (SELECT id from studio where name = 'Sony Interactive Entertainment')),
('Dragon Quest VII', '2000-08-26', 'RPG', 'images/DragonQuestVII.png', '9.5',
 'Dragon Quest VII: Fragments of the Forgotten Past[a] is a Japanese role-playing video game developed by Heartbeat[4] and ArtePiazza,[5] and published by Enix for the PlayStation in 2000.',
 (SELECT id from studio where name = 'Sony Interactive Entertainment')),
('Final Fantasy VII', '1997-01-31', 'RPG', 'images/FinalFantasyVII.png', '9.5',
 'Final Fantasy VII[a] is a 1997 role-playing video game developed by Square for the PlayStation console. It is the seventh installment in the Final Fantasy series.',
 (SELECT id from studio where name = 'Sony Interactive Entertainment')),
('GoldenEye 007', '1997-08-25', 'FPP', 'images/GoldeEye007.png', '8.5',
 'Final Fantasy VII[a] is a 1997 role-playing video game developed by Square for the PlayStation console. It is the seventh installment in the Final Fantasy series.',
 (SELECT id from studio where name = 'Nintendo')),
('Gradius Gaiden', '1997-08-28', 'ARCADE', 'images/GradiusGaiden.png', '8.5',
 'Gradius Gaiden[a] is a 1997 horizontal-scrolling shooter video game developed and published for the PlayStation by Konami.',
 (SELECT id from studio where name = 'Konami')),
('Gran Turismo', '1997-12-23', 'RACER', 'images/GranTurismo.png', '9.0',
 'Gran Turismo is a sim racing video game designed by Kazunori Yamauchi. Gran Turismo was developed by Polys Entertainment and published by Sony Computer Entertainment in 1997 for the PlayStation video game console. ',
 (SELECT id from studio where name = 'Polyphony Digital')),
('The Legend of Zelda: Ocarina of Time', '1998-11-21', 'RPG', 'images/LegendofZelda.png', '10.0',
 'The Legend of Zelda: Ocarina of Time[a] is an action-adventure game developed and published by Nintendo for the Nintendo 64.',
 (SELECT id from studio where name = 'Nintendo')),
('Metal Gear Solid', '1998-08-03', 'TPP', 'images/MetalGearSolid.png', '10.0',
 'Metal Gear Solid[a] is a stealth game developed by Konami and released for the PlayStation in 1998.',
 (SELECT id from studio where name = 'Konami')),
('The Need for Speed', '1994-08-31', 'RACER', 'images/NeedForSpeed.png', '8.5',
 'Road & Track Presents: The Need for Speed is a racing video game developed by EA Canada and published by Electronic Arts, initially released on the 3DO in 1994, and ported to MS-DOS in 1995.',
 (SELECT id from studio where name = 'Electronic Arts')),
('Nights into Dreams', '1996-07-05', 'ARCADE', 'images/NightsIntoDreams.png', '9.5',
 'Nights into Dreams[a] is a 1996 action game developed by Sonic Team and published by Sega for the Sega Saturn.',
 (SELECT id from studio where name = 'Sega')),
('Panzer Dragoon Saga', '1998-01-29', 'RPG', 'images/PanzerDragoonSaga.png', '9.5',
 'Panzer Dragoon Saga, known in Japan as Azel: Panzer Dragoon RPG,[1] is a 1998 role-playing video game published by Sega and developed by Team Andromeda for the Sega Saturn.',
 (SELECT id from studio where name = 'Sega')),
('Pokémon Red and Blue', '1996-02-27', 'RPG', 'images/Pokemon.png', '9.5',
 'Pokémon Red Version and Pokémon Blue Version are 1996 role-playing video games developed by Game Freak and published by Nintendo for the Game Boy.',
 (SELECT id from studio where name = 'Game Freak')),
('Resident Evil', '1996-03-22', 'TPP', 'images/ResidentEvil.png', '9.5',
 'Resident Evil[b] is a survival horror video game developed and released by Capcom originally for the PlayStation in 1996, and is the first game in the Resident Evil series.',
 (SELECT id from studio where name = 'Capcom')),
('Tomb Raider', '1996-10-25', 'TPP', 'images/TombRaider.png', '9.0',
 'Tomb Raider is a 1996 action-adventure video game developed by Core Design and published by Eidos Interactive.',
 (SELECT id from studio where name = 'Core Design')),
('Radiant Silvergun', '1998-05-01', 'FPP', 'images/RadiantSilvergun.png', '9.0',
 'Radiant Silvergun[a] is a shoot ''em up developed by Treasure. It was originally released in Japanese arcades in 1998 and subsequently ported to the Sega Saturn later that year.',
 (SELECT id from studio where name = 'Treasure')),
('Tony Hawk''s Pro Skater 2', '2000-08-20', 'Sport', 'images/TonyHawk2.png', '9.0',
 'Tony Hawk''s Pro Skater 2 is a skateboarding video game developed by Neversoft and published by Activision. ',
 (SELECT id from studio where name = 'Activision'));